apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/argocd-roles
  - https://github.com/redhat-appstudio/application-service/config/default?ref=a32c938ee1fcafaed4c64abd3ed4864121fd363c


components:
  - ../../components/manager-resources
  - ../../components/enable-profiling

images:
  - name: quay.io/redhat-appstudio/application-service
    newName: quay.io/redhat-appstudio/application-service
    newTag: 05ee33115e4cd7ebfad61d96ffe5ef36c8159dab

configMapGenerator:
  - literals:
      - GITHUB_ORG=""
    name: github-config
    behavior: replace



namespace: application-service